limitNamespace: false

ingress:
  enabled: false
  # annotations: 
  #   kubernetes.io/ingress.class: nginx
  # hosts:
  #   - host: kubeview.example.net
  #     paths: 
  #       - /
  # tls:
  #  - secretName: my-cert
  #    hosts:
  #      - kubeview.example.net
