#
# Deploy the back end data API microservice in Kubernetes
# Basic version
#

# ------------------- Deployment ------------------- #

kind: Deployment
apiVersion: apps/v1
metadata:
  name: kubeview
  labels:
    app: kubeview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeview
  template:
    metadata:
      labels:
        app: kubeview
    spec:
      serviceAccountName: kubeview
      containers:
      - name: kubeview-containers

        image: bencuk/kubeview:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 3000

        resources:
          limits:
            memory: "128M"
            cpu: "0.1"

--- 

# ------------------- Loadbalancer ------------------- #

kind: Service
apiVersion: v1
metadata:
  name: kubeview
  annotations:
    # !CHANGE THIS! To your real DNS domain
    external-dns.alpha.kubernetes.io/hostname: kubeview.f0dfafed36164c7faac0.westeurope.aksapp.io
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    app: kubeview