name: Release Dockerhub Image

on:
  release:
    types: [published]
    
env:
  dockerUser: bencuk
  imageName: kubeview
  
jobs:
  releaseJob:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Build the Docker image
      run: docker build . --file ./build/Dockerfile --tag $dockerUser/$imageName:${{ github.event.release.tag_name }}
    
    - name: Login to Dockerhub
      if: github.repository == 'benc-uk/kubeview' && github.event_name == 'push'
      run: docker login -u $dockerUser -p ${{ secrets.dockerPassword }} 
      
    - name: Push to Dockerhub
      if: github.repository == 'benc-uk/kubeview' && github.event_name == 'push'
      run: docker push $dockerUser/$imageName:${{ github.event.release.tag_name }}
